Repository w3c/aria-practices, pull requests merged in 2019-01, with the labels that each got.

#952 Radio Group Pattern: Add new keyboard interaction for radios in toolbars
  aria-practices.html
Labels: enhancement, pattern

#957 Add carousel pattern
  aria-practices.html
Labels: documentation, pattern

#950 Add redesigned toolbar example
  examples/toolbar/css/menuButton.css
  examples/toolbar/css/toolbar.css
  examples/toolbar/help.html
  examples/toolbar/images/menuitemradio-checked.svg
  examples/toolbar/images/menuitemradio-unchecked.svg
  examples/toolbar/images/pulldown-icon-focus.svg
  examples/toolbar/images/pulldown-icon.svg
  examples/toolbar/js/FontMenu.js
  examples/toolbar/js/FontMenuButton.js
  examples/toolbar/js/FontMenuItem.js
  examples/toolbar/js/FormatToolbar.js
  examples/toolbar/js/FormatToolbarItem.js
  examples/toolbar/js/SpinButton.js
  examples/toolbar/js/main.js
  examples/toolbar/js/menuButton.js
  examples/toolbar/js/toolbar.js
  examples/toolbar/toolbar.html
  test/tests/toolbar.js
  test/util/assertRovingTabindex.js
Labels: Needs Review, code example, enhancement
