Repository w3c/aria-practices, pull requests merged in 2021-11, with the labels that each got.

#2056 Radio Example: Add scroll-to feature using aria-activedescendant
  examples/radio/js/radio-activedescendant.js
  examples/radio/radio-activedescendant.html
Labels: example of pattern implementation, QA for APG Examples

#2068 Infrastructure: Update for github-script@v5
  .github/workflows/coverage-report.yml
Labels: Infrastructure

#2075 Grid Combobox Example: Add scroll into view feature
  examples/combobox/grid-combo.html
  examples/combobox/js/grid-combo.js
Labels: example of pattern implementation

#2085 Landmarks Example: Update link to the "SkipTo Landmark and Headings" Chrome extension
  examples/landmarks/at.html
Labels: example of pattern implementation

#2086 Combobox Autocomplete Example: Use pointer events instead of mouse events
  examples/combobox/js/combobox-autocomplete.js
Labels: example of pattern implementation

#2087 Infrastructure: fix missing package-lock resolutions
  package-lock.json
Labels: Infrastructure

#2084 Infrastructure: Use npm cache in setup-node
  .github/workflows/coverage-report.yml
  .github/workflows/examples.yml
  .github/workflows/lint-css.yml
  .github/workflows/lint-html.yml
  .github/workflows/lint-js.yml
  .github/workflows/regression.yml
  .github/workflows/spelling.yml
Labels: Infrastructure

#2081 Infrastructure: Move Depednabot updates weekly
  .github/dependabot.yml
Labels: Infrastructure

#2080 Infrastructure: Upgrade ESLint to v8 and plugins
  .eslintrc.json
  package-lock.json
  package.json
  test/tests/combobox_autocomplete-both.js
  test/tests/combobox_autocomplete-list.js
  test/tests/combobox_datepicker.js
  test/tests/grid_LayoutGrids.js
  test/tests/listbox_rearrangeable.js
Labels: Infrastructure

#2078 Infrastructure: Update Husky v7 and script changes
  .husky/_/husky.sh
  package-lock.json
  package.json
Labels: Infrastructure

#2083 Infrastructure: vnu-jar problem matcher update
  .github/workflows/vnu-jar-problem-matcher.json
Labels: Infrastructure

#2077 Infrastructure: Update Stylelint
  .stylelintrc
  examples/accordion/css/accordion.css
  examples/alert/css/alert.css
  examples/breadcrumb/css/breadcrumb.css
  examples/button/css/button.css
  examples/carousel/css/carousel-prev-next.css
  examples/carousel/css/carousel-tablist.css
  examples/combobox/css/combobox-autocomplete.css
  examples/combobox/css/combobox-datepicker.css
  examples/combobox/css/grid-combo.css
  examples/combobox/css/select-only.css
  examples/css/core.css
  examples/css/github.css
  examples/dialog-modal/css/datepicker-dialog.css
  examples/dialog-modal/css/dialog.css
  examples/disclosure/css/disclosure-navigation.css
  examples/grid/css/dataGrids.css
  examples/grid/css/layoutGrids.css
  examples/landmarks/css/bootstrap-accessibility.css
  examples/landmarks/css/common.css
  examples/landmarks/css/visua11y.css
  examples/link/css/link.css
  examples/listbox/css/listbox.css
  examples/menubar/css/menubar-navigation.css
  examples/radio/css/radio.css
  examples/slider/css/slider-color-viewer.css
  examples/slider/css/slider-multithumb.css
  examples/switch/css/switch.css
  examples/tabs/css/tabs.css
  examples/toolbar/css/menuButton.css
  examples/toolbar/css/toolbar.css
  examples/treegrid/css/treegrid-1.css
  package-lock.json
  package.json
Labels: Infrastructure

#1870 Radio Group: Rating Example
  aria-practices.html
  examples/index.html
  examples/radio/css/radio-rating.css
  examples/radio/js/radio-rating.js
  examples/radio/radio-activedescendant.html
  examples/radio/radio-rating.html
  examples/radio/radio.html
  examples/slider/slider-rating.html
  test/tests/radio_radio-rating.js
Labels: example of pattern implementation

#2125 Switch example using checkbox: Remove browser prefixes from CSS and fix stylelint errors
  examples/switch/css/switch-checkbox.css
Labels: example of pattern implementation, Code Quality

#2127 Infrastructure: Update Respec Profile
  aria-practices.html
  respec-config.js
Labels: Infrastructure

#2108 Infrastructure: remove npm-merge-driver and update to lockfileVersion: 2
  package-lock.json
  package.json
Labels: Infrastructure, dependencies

#2120 Feed Example Display Page: Change h2 to h1
  examples/feed/feedDisplay.html
Labels: example of pattern implementation, QA for APG Examples

#2119 Listbox Examples: Correct skipped heading level issue; change some h4 to h3.
  examples/listbox/listbox-collapsible.html
  examples/listbox/listbox-rearrangeable.html
  examples/listbox/listbox-scrollable.html
Labels: example of pattern implementation, QA for APG Examples

#2138 Editable Combobox Examples: Correct enter key documentation for the autocomplete none and list implementations
  examples/combobox/combobox-autocomplete-list.html
  examples/combobox/combobox-autocomplete-none.html
Labels: documentation, example of pattern implementation, Inaccuracy

#2139 Combobox example with grid popup: Correct documentation of aria-selected
  examples/combobox/grid-combo.html
Labels: documentation, example of pattern implementation, Inaccuracy

#2144 Checkbox Examples: Update links and descriptions
  aria-practices.html
  examples/checkbox/checkbox-mixed.html
  examples/checkbox/checkbox.html
Labels: editorial, example of pattern implementation, QA for APG Examples

#1876 Add CodePen button to menubar-editor and avoid external SVG
  examples/index.html
  examples/menubar/css/menubar-editor.css
  examples/menubar/css/menubar-navigation.css
  examples/menubar/images/checkbox-checked-focus.svg
  examples/menubar/images/checkbox-checked.svg
  examples/menubar/images/down-arrow-focus.svg
  examples/menubar/images/down-arrow.svg
  examples/menubar/images/radio-checked-focus.svg
  examples/menubar/images/radio-checked.svg
  examples/menubar/images/separator.svg
  examples/menubar/images/up-arrow-focus.svg
  examples/menubar/images/up-arrow.svg
  examples/menubar/js/menubar-editor.js
  examples/menubar/js/menubar-navigation.js
  examples/menubar/js/style-manager.js
  examples/menubar/menubar-editor.html
  examples/menubar/menubar-navigation.html
  test/tests/menubar_menubar-editor.js
Labels: Needs Review, agenda

#2137 Listbox Pattern: Add option grouping and update selection guidance
  aria-practices.html
Labels: documentation, pattern section
