Repository w3c/aria-practices, pull requests merged in 2022-05, with the labels that each got.

#2286 Developing Keyboard Interface - Managing Focus in Composites Using aria-activedescendant: Update DOM relationship requirements to match ARIA 1.2
  aria-practices.html
Labels: editorial, documentation, Inaccuracy

#2240 Multiple Examples: Change CSS currentColor to currentcolor
  examples/accordion/css/accordion.css
  examples/breadcrumb/css/breadcrumb.css
  examples/button/button.html
  examples/button/button_idl.html
  examples/checkbox/checkbox-mixed.html
  examples/checkbox/checkbox.html
  examples/checkbox/css/checkbox-mixed.css
  examples/checkbox/css/checkbox.css
  examples/combobox/combobox-autocomplete-both.html
  examples/combobox/combobox-autocomplete-list.html
  examples/combobox/combobox-autocomplete-none.html
  examples/combobox/css/combobox-autocomplete.css
  examples/disclosure/css/disclosure-faq.css
  examples/disclosure/css/disclosure-image-description.css
  examples/disclosure/disclosure-faq.html
  examples/disclosure/disclosure-image-description.html
  examples/listbox/css/listbox.css
  examples/menu-button/css/menu-button-actions.css
  examples/menu-button/css/menu-button-links.css
  examples/menu-button/menu-button-actions-active-descendant.html
  examples/menu-button/menu-button-actions.html
  examples/menu-button/menu-button-links.html
  examples/menubar/css/menubar-navigation.css
  examples/menubar/menubar-navigation.html
  examples/meter/meter.html
  examples/radio/css/radio-rating.css
  examples/radio/radio-rating.html
  examples/slider/css/slider-color-viewer.css
  examples/slider/css/slider-multithumb.css
  examples/slider/css/slider-rating.css
  examples/slider/css/slider-seek.css
  examples/slider/css/slider-temperature.css
  examples/slider/slider-color-viewer.html
  examples/slider/slider-multithumb.html
  examples/slider/slider-rating.html
  examples/slider/slider-seek.html
  examples/slider/slider-temperature.html
  examples/switch/css/switch-button.css
  examples/switch/switch-button.html
  examples/table/css/sortable-table.css
  examples/treeview/css/treeview-navigation.css
  examples/treeview/treeview-navigation.html
  package-lock.json
  package.json
Labels: enhancement, dependencies, Code Quality

#2323 Home Page: Remove current work section and revise contribution section
  index.html
Labels: editorial, Site Design

#2326 Repository ReadMe.md: Update to remove information related to APG as a W3C Note published to TR
  README.md
Labels: documentation
