Repository w3c/aria-practices, pull requests merged in 2024-05, with the labels that each got.

#2961 Infrastructure: Bump eslint from 8.52.0 to 8.57.0, eslint-plugin-jsdoc from 39.3.3 to 48.2.3, eslint-plugin-html from 6.2.0 to 8.1.1, eslint-config-prettier from 8.5.0 to 9.1.0, eslint-plugin-prettier from 4.2.1 to 5.1.3, eslint-plugin-ava from 13.2.0 to 14.0.0, and prettier from 2.7.1 to 3.2.5
  .eslintrc.json
  .prettierrc
  content/patterns/alertdialog/examples/css/alertdialog.css
  content/patterns/dialog-modal/examples/css/dialog.css
  package-lock.json
  package.json
  scripts/coverage-report.js
  test/tests/accordion_accordion.js
  test/tests/treeview_treeview-navigation.js
  test/util/assertAriaDescribedby.js
Labels: Infrastructure, dependencies

#2959 Infrastructure: Update @babel/core from 7.23.2 to 7.24.5 and @babel/eslint-parser from 7.22.15 to 7.24.5
  package-lock.json
  package.json
Labels: Infrastructure, dependencies

#2997 Regression Tests: Enable `disclosure_navigation.js` test to scroll to element
  test/tests/disclosure_navigation.js
Labels: regression-testing

#3014 Infrastructure: Use Stylelint GitHub Action matcher
  .github/workflows/lint-css.yml
Labels: Infrastructure

#3000 About: Add page to about section that explains the AT support tables
  content/about/about.html
  content/about/at-support-tables/at-support-tables.html
  content/patterns/alert/examples/alert.html
  content/patterns/button/examples/button.html
  content/patterns/dialog-modal/examples/dialog.html
  content/patterns/link/examples/link.html
  content/patterns/menu-button/examples/menu-button-links.html
  content/patterns/radio/examples/radio-activedescendant.html
  content/patterns/slider/examples/slider-color-viewer.html
Labels: enhancement

#3026 Infrastructure: Exclude `skipto.js` in `coverage-report.js` and report accurate values in Coverage and Quality Reports
  content/about/coverage-and-quality/coverage-and-quality-report.html
  scripts/coverage-report.js
Labels: bug
