Repository w3c/aria-practices, pull requests merged in 2024-07, with the labels that each got.

#3048 Infrastructure: Re-run `npm run reference-tables` and `npm run coverage-report` on source script update
  package.json
Labels: Infrastructure

#3059 Regression Tests: Enable `disclosure_navigation.js` test to scroll to element and click in `executeScript` context
  test/tests/disclosure_navigation.js
Labels: regression-testing

#3011 Infrastructure: Upgrade to ESLint 9
  .eslintignore
  .eslintrc.json
  .link-checker.js
  content/patterns/grid/examples/js/dataGrid.js
  eslint.config.mjs
  package-lock.json
  package.json
  scripts/link-checker.js
Labels: Infrastructure, dependencies
