Repository w3c/aria-practices, pull requests merged in 2025-09, with the labels that each got.

#3320 Pattern Pages: Show link to "Read This First" just after the H1 on each pattern page
  content/patterns/accordion/accordion-pattern.html
  content/patterns/alert/alert-pattern.html
  content/patterns/alertdialog/alertdialog-pattern.html
  content/patterns/breadcrumb/breadcrumb-pattern.html
  content/patterns/button/button-pattern.html
  content/patterns/carousel/carousel-pattern.html
  content/patterns/checkbox/checkbox-pattern.html
  content/patterns/combobox/combobox-pattern.html
  content/patterns/dialog-modal/dialog-modal-pattern.html
  content/patterns/disclosure/disclosure-pattern.html
  content/patterns/feed/feed-pattern.html
  content/patterns/grid/grid-pattern.html
  content/patterns/landmarks/landmarks-pattern.html
  content/patterns/link/link-pattern.html
  content/patterns/listbox/listbox-pattern.html
  content/patterns/menu-button/menu-button-pattern.html
  content/patterns/menubar/menu-and-menubar-pattern.html
  content/patterns/meter/meter-pattern.html
  content/patterns/patterns.html
  content/patterns/radio/radio-group-pattern.html
  content/patterns/slider-multithumb/slider-multithumb-pattern.html
  content/patterns/slider/slider-pattern.html
  content/patterns/spinbutton/spinbutton-pattern.html
  content/patterns/switch/switch-pattern.html
  content/patterns/table/table-pattern.html
  content/patterns/tabs/tabs-pattern.html
  content/patterns/toolbar/toolbar-pattern.html
  content/patterns/tooltip/tooltip-pattern.html
  content/patterns/treegrid/treegrid-pattern.html
  content/patterns/treeview/treeview-pattern.html
  content/patterns/windowsplitter/windowsplitter-pattern.html
  content/practices/practices.html
  content/shared/js/read-this-first.js
  content/shared/templates/read-this-first.html
Labels: Infrastructure

#3354 Infrastructure: Temp fix to regression test - Fix `toolbar_toolbar.js` by resetting menu button state
  test/tests/toolbar_toolbar.js
Labels: regression-testing

#3356 Grid Pattern: Correct error in description of left/right arrow behavior when navigating inside a cell
  content/patterns/grid/grid-pattern.html
Labels: editorial, Feedback, Pattern Page

#3365 Infrastructure: Remove 'id=' from cspell's ignoreRegExpList
  cspell.json
Labels: Infrastructure

#3366 Developing a Keyboard Interface Practice: Editorial revision to note about pointer considerations
  content/practices/keyboard-interface/keyboard-interface-practice.html
Labels: editorial
